name: Deploy to Google Cloud Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE: moai-scm-suite
  REGION: asia-northeast1
  REGISTRY: gcr.io

jobs:
  deploy:
    # Add "id-token" with the intended permissions for Workload Identity Federation
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Google Auth using Workload Identity Federation
      id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SA_EMAIL }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker to use gcloud as credential helper
      run: |-
        gcloud --quiet auth configure-docker

    - name: Build Docker image
      run: |-
        docker build -t "${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}" .

    - name: Push Docker image
      run: |-
        docker push "${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}"

    - name: Deploy to Cloud Run
      id: deploy
      run: |-
        gcloud run deploy ${{ env.SERVICE }} \
          --image=${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }} \
          --region=${{ env.REGION }} \
          --platform=managed \
          --allow-unauthenticated \
          --memory=2Gi \
          --cpu=2 \
          --timeout=300 \
          --set-env-vars="GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }},OSRM_HOST=test-osrm-intel.aq-cloud.com"

    - name: Show Output
      run: |-
        echo "🎉 Deployment complete!"
        gcloud run services describe ${{ env.SERVICE }} \
          --region=${{ env.REGION }} \
          --format='value(status.url)' || echo "Service URL not available yet"